export const INCREMENTS_INGREDIENT = 'INCREMENTS_INGREDIENT';
export const DECREMENTS_INGREDIENT = 'DECREMENTS_INGREDIENT';
export const INCREMENTS_BUNS = 'INCREMENTS_BUNS';
export const RESET_COUNTERS = 'RESET_COUNTERS';
